#!/bin/bash
# Script to help update Vercel Root Directory

echo "🔧 Vercel Root Directory Update Helper"
echo ""
echo "The Root Directory field might be in different locations:"
echo ""
echo "📍 Location 1: Settings → General"
echo "   1. Go to: https://vercel.com/mtuneccesarys-projects/frontend/settings"
echo "   2. Click 'General' tab (if visible)"
echo "   3. Look for 'Root Directory' field"
echo ""
echo "📍 Location 2: Settings → Build & Development Settings"
echo "   1. Go to: https://vercel.com/mtuneccesarys-projects/frontend/settings"
echo "   2. Look for tabs: 'Build & Development Settings' or 'Build Settings'"
echo "   3. Find 'Root Directory' or 'Base Directory' field"
echo ""
echo "📍 Location 3: Project Overview → Configure"
echo "   1. Go to: https://vercel.com/mtuneccesarys-projects/frontend"
echo "   2. Look for 'Configure' or 'Settings' button"
echo "   3. Find 'Root Directory' in configuration"
echo ""
echo "💡 What to set:"
echo "   Current: . (or empty)"
echo "   Change to: packages/frontend"
echo ""
echo "🔄 After updating, redeploy from:"
echo "   https://vercel.com/mtuneccesarys-projects/frontend/deployments"
